# Generated by Django 3.2.9 on 2021-11-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=45, null=True)),
                ('senha', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf', models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=11, null=True)),
                ('nis', models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=11, null=True)),
                ('pais', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('rua', models.CharField(blank=True, max_length=30, null=True)),
                ('cep', models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=8, null=True)),
                ('numero', models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
