# Generated by Django 3.2.9 on 2021-11-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='user',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='user',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='user',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rua',
        ),
    ]
