# Generated by Django 3.2.9 on 2021-11-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211115_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cep',
            field=models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='complemento',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='estado',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='numero',
            field=models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pais',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rua',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
