# Generated by Django 3.2.9 on 2021-11-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211115_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cep',
            field=models.DecimalField(blank=True, decimal_places=0, default='', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.DecimalField(blank=True, decimal_places=0, default='', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nis',
            field=models.DecimalField(blank=True, decimal_places=0, default='', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='numero',
            field=models.DecimalField(blank=True, decimal_places=0, default='', max_digits=10, null=True),
        ),
    ]
